---
abstract: '(DEPRECATED) installing and finding script.aculo.us'
author:
  - 'Graham TerMarsch (cpan@howlingfrog.com)'
build_requires:
  Archive::Tar: '0'
  Test::Exception: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-scriptaculous
provides:
  Alien::scriptaculous:
    file: lib/Alien/scriptaculous.pm
    version: v1.8.0.2
requires:
  Alien::Prototype: v1.6.0
  perl: v5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: v1.8.0.2
x_bugtracker:
  web: https://github.com/bleargh45/Alien-scriptaculous/issues
x_deprecated: 1
x_repository:
  type: git
  url: git://github.com/bleargh45/Alien-scriptaculous.git
  web: https://github.com/bleargh45/Alien-scriptaculous
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
